name: Build Linux
run-name: Build Linux
on: ["push"]
jobs:
  Build-Linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download libcronet
        run: ./libcronet.sh
      - name: Build
        run: python3 -m build
