name: Build Linux
run-name: Build Linux
on: ["push"]
jobs:
  Build-Linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download libcronet
        run: ./libcronet.sh
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Build
        run: pip install build && python -m build
      - uses: actions/upload-artifact@v4
        with:
          name: cronet-0.0.1-cp312-cp312-linux_x86_64.whl
          path: dist/cronet-0.0.1-cp312-cp312-linux_x86_64.whl
