name: Build Linux
run-name: Build Linux
on: ["push"]
jobs:
  Build-Linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download libcronet
        run: ./libcronet.sh
      - name: Create virtualenv
        run: virtualenv -p python3 venv
      - name: Build
        run: ./venv/bin/pip install build && ./venv/bin/python -m build

