name: Build linux

on: [push]

jobs:    
  build_wheels:
    name: Build wheels for linux
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 10000
          swap-size-mb: 1024
          remove-dotnet: 'true'
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build wheels
        run: docker run -t -e PLAT=manylinux_2_28_x86_64 -e CHROMIUM=122.0.6261.111 -e VERSION=0.0.1 -v `pwd`:/app quay.io/pypa/manylinux_2_28_x86_64 /app/libcronet/build.sh
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: wheels
          path: ./wheelhouse/*.whl
