name: Build cronet
run-name: Build cronet
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: rm -rf /opt/hostedtoolcache
      - run: git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
      - run: echo PATH="$(pwd)/depot_tools:$PATH" >> $GITHUB_ENV
      - run: git clone --depth 1 --single-branch --branch 122.0.6261.90 https://chromium.googlesource.com/chromium/src.git
        working-directory: ./chromium
      - run: gclient config https://chromium.googlesource.com/chromium/src.git
        working-directory: ./chromium
      - run: echo 'target_os = ["linux"]' >> .gclient
        working-directory: ./chromium
      - run: gclient sync
        working-directory: ./chromium
      - run: ./build/install-build-deps.sh
        working-directory: ./chromium/src/
      - run: gn gen out/Cronet
        working-directory: ./chromium/src/components/cronet
      - run: ninja -C out/Cronet cronet_package
        working-directory: ./chromium/src/components/cronet
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: cronet
          path: ./chromium/src/components/cronet/out/Cronet
