name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
      - run: echo PATH="$(pwd)/depot_tools:$PATH" >> $GITHUB_ENV
      - run: mkdir chromium && cd chromium
      - run: fetch --nohooks --no-history chromium
      - run: cd src
      - run: /build/install-build-deps.sh
      - run: gclient runhooks
